#### Biary Classification for Lung Cancer
In this excercise we would develop a model that would take values from user and check wether there is chance of cancer to this person or not.

To develop such an model I am using lung_cancer dataset that contains values like Gender, Age, Smooking, CHEST PAIN etc.

> Out dataset is not completely cleaned or maintained so we need to do some data analysis to the dataset, we must convert the dataset into numberic values

In [77]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [50]:
dataset = pd.read_csv("lung_cancer.csv")
dataset.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO

In [51]:
dataset["GENDER"] = dataset["GENDER"].astype('category')
dataset["GENDER"] = dataset["GENDER"].cat.codes
dataset["LUNG_CANCER"] = dataset["LUNG_CANCER"].astype('category')
dataset["LUNG_CANCER"] = dataset["LUNG_CANCER"].cat.codes
dataset.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,1,69,1,2,2,1,1,2,1,2,2,2,2,2,2,1
1,1,74,2,1,1,1,2,2,2,1,1,1,2,2,2,1
2,0,59,1,1,1,2,1,2,1,2,1,2,2,1,2,0
3,1,63,2,2,2,1,1,1,1,1,2,1,1,2,2,0
4,0,63,1,2,1,1,1,1,1,2,1,2,2,1,1,0

In [52]:
dataset.isnull().sum()

GENDER                   0
AGE                      0
SMOKING                  0
YELLOW_FINGERS           0
ANXIETY                  0
PEER_PRESSURE            0
CHRONIC DISEASE          0
FATIGUE                  0
ALLERGY                  0
WHEEZING                 0
ALCOHOL CONSUMING        0
COUGHING                 0
SHORTNESS OF BREATH      0
SWALLOWING DIFFICULTY    0
CHEST PAIN               0
LUNG_CANCER              0
dtype: int64

#### Data is ready
our dataset is cleaned and ready to work as it only contains numeric data for all values, but it contains some unecesorry values. so let's get only required values

In [53]:
dataset = dataset[["GENDER","AGE","SMOKING","ANXIETY","ALLERGY","ALCOHOL CONSUMING","COUGHING","SHORTNESS OF BREATH","CHEST PAIN","LUNG_CANCER"]]
dataset.head()

,GENDER,AGE,SMOKING,ANXIETY,ALLERGY,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,CHEST PAIN,LUNG_CANCER
0,1,69,1,2,1,2,2,2,2,1
1,1,74,2,1,2,1,1,2,2,1
2,0,59,1,1,1,1,2,2,2,0
3,1,63,2,2,1,2,1,1,2,0
4,0,63,1,1,1,1,2,2,1,0

#### Let's Get X and y

In [54]:
X = dataset.drop(columns= "LUNG_CANCER")
y = dataset["LUNG_CANCER"]

In [55]:
X.head()

,GENDER,AGE,SMOKING,ANXIETY,ALLERGY,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,CHEST PAIN
0,1,69,1,2,1,2,2,2,2
1,1,74,2,1,2,1,1,2,2
2,0,59,1,1,1,1,2,2,2
3,1,63,2,2,1,2,1,1,2
4,0,63,1,1,1,1,2,2,1

In [56]:
X.shape

(309, 9)

In [57]:
y.head()

0    1
1    1
2    0
3    0
4    0
Name: LUNG_CANCER, dtype: int8

#### Split data into Training and Testing

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [59]:
X_train.shape

(247, 9)

#### Transform Data
Transform X_train and X_test through Standerd Scaler to manage the standered deviation

When we fit data to standered scaler it calculates the mean standered deviation of the data to be able to calculate the Z. It uses the training dataset to calculate these parameters

In [60]:
# scaler = StandardScaler()
# But I don't want to do that as already I have done with my dataset cleaning process

In [61]:
#X_train_Scaled = scaler.fit_transform(X_train)

In [62]:
#X_test_Scaled = scaler.transform(X_test)

#### Let's Check our scaled data

Our data would look similer to each other not the too much high or low values. and also it converts the dataset format (series format) to 2D array

#### Lets fit the data to Model now

In [63]:
log_model = LogisticRegression(random_state=0,C=1,fit_intercept=False,max_iter=100)

In [64]:
log_model.fit(X_train, y_train)

LogisticRegression(C=1, fit_intercept=False, random_state=0)

#### Let's check by new data to predict

In [65]:
y_predicton = log_model.predict(X_test)

In [66]:
y_predicton

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

#### Let's Check score

In [67]:
log_model.score(X_train, y_train)*100

89.47368421052632

In [68]:
log_model.score(X_test, y_test)*100

83.87096774193549

In [69]:
log_model.score(X_test, y_predicton)*100

100.0

#### Let's check the probability of Cancer

In [95]:
result = np.round(log_model.predict_proba([[1,45,1,1,1,1,1,1,1]]))
# 0 => No
# 1 => Yes
print(f"Proability of Cancer is : {result}")

Proability of Cancer is : [[0. 1.]]

c:\Users\Sakhi Larik\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [98]:
result = np.round(log_model.predict_proba([[1,15,1,0,0,0,1,1,0]]))
# 0 => No
# 1 => Yes
print(f"Proability of Cancer is : {result[0][1]}")

Proability of Cancer is : 0.0

c:\Users\Sakhi Larik\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [99]:
result = np.round(log_model.predict_proba([[0,15,1,1,1,1,1,1,1]]))
# 0 => No
# 1 => Yes
print(f"Proability of Cancer is : {result[0][1]}")

Proability of Cancer is : 1.0

c:\Users\Sakhi Larik\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

#### Let's check the model
Let's check the model by adding some new values to predict the cancer of the person by considering

GENDER,	AGE, SMOKING, ANXIETY, ALLERGY, ALCOHOL, CONSUMING, COUGHING, SHORTNESS OF BREATH, CHEST PAIN

In [70]:
print(f"Chances of Cancer to this persion is {log_model.predict([[1,45,1,1,1,1,1,1,1]])}")

Chances of Cancer to this persion is [1]

c:\Users\Sakhi Larik\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [71]:
print(f"Chances of Cancer to this persion is {log_model.predict([[1,15,1,0,0,0,1,1,0]])}")

Chances of Cancer to this persion is [0]

c:\Users\Sakhi Larik\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [72]:
print(f"Chances of Cancer to this persion is {log_model.predict([[0,15,1,1,1,1,1,1,1]])}")

Chances of Cancer to this persion is [1]

c:\Users\Sakhi Larik\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [73]:
print(f"Chances of Cancer to this persion is {log_model.predict([[1,75,0,0,0,0,0,0,0]])}")

c:\Users\Sakhi Larik\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

Chances of Cancer to this persion is [0]